<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import type { StoredScenario } from '../types';

const props = defineProps<{
  scenario?: StoredScenario | null;
  visible: boolean;
}>();

const emit = defineEmits<{
  save: [title: string, description: string];
  cancel: [];
}>();

const title = ref('');
const description = ref('');

const isEditing = computed(() => !!props.scenario);
const modalTitle = computed(() =>
  isEditing.value ? 'シナリオ編集' : '新規シナリオ登録'
);

// Title is optional, only description is required
const canSave = computed(() => description.value.trim().length > 0);

// Title placeholder: shows auto-generated preview
const titlePlaceholder = computed(() => {
  if (description.value.trim()) {
    const firstLine = description.value.split('\n')[0].trim();
    const preview =
      firstLine.length > 20 ? firstLine.substring(0, 20) + '...' : firstLine;
    return `未入力の場合: 「${preview}」`;
  }
  return 'タイトル（省略可 - 本文から自動生成）';
});

watch(
  () => props.scenario,
  (newVal) => {
    if (newVal) {
      title.value = newVal.title;
      description.value = newVal.description;
    } else {
      title.value = '';
      description.value = '';
    }
  },
  { immediate: true }
);

watch(
  () => props.visible,
  (newVal) => {
    if (!newVal) {
      title.value = '';
      description.value = '';
    }
  }
);

function handleSave() {
  if (!canSave.value) return;
  // Title can be empty - will be auto-generated by service
  emit('save', title.value.trim(), description.value.trim());
}
</script>

<template>
  <div v-if="visible" class="modal-overlay" @click.self="$emit('cancel')">
    <div class="modal scenario-form-modal">
      <h2>{{ modalTitle }}</h2>
      <div class="form-group">
        <label for="title-input"
          >タイトル <span class="optional-label">（省略可）</span></label
        >
        <input
          id="title-input"
          v-model="title"
          type="text"
          :placeholder="titlePlaceholder"
        />
        <p class="hint-text">
          未入力の場合、シナリオ内容の先頭から自動生成されます
        </p>
      </div>
      <div class="form-group">
        <label for="description-input"
          >シナリオ内容 <span class="required-label">*</span></label
        >
        <textarea
          id="description-input"
          v-model="description"
          rows="10"
          placeholder="テストシナリオの詳細を入力...

例:
1. Chromeを開く
2. google.comにアクセス
3. 'Tauri framework'を検索"
        ></textarea>
      </div>
      <div class="button-row">
        <button @click="$emit('cancel')" class="secondary-button">
          キャンセル
        </button>
        <button @click="handleSave" class="primary-button" :disabled="!canSave">
          {{ isEditing ? '保存' : '登録' }}
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}
.modal {
  background: white;
  padding: 24px;
  border-radius: 12px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
  width: 90%;
  max-width: 600px;
}
@media (prefers-color-scheme: dark) {
  .modal {
    background: #2a2a2a;
    color: #f6f6f6;
  }
}
.scenario-form-modal h2 {
  margin-top: 0;
  margin-bottom: 20px;
}
.form-group {
  margin-bottom: 16px;
}
.form-group label {
  display: block;
  margin-bottom: 6px;
  font-weight: 500;
}
.optional-label {
  font-weight: normal;
  color: #888;
  font-size: 0.9em;
}
.required-label {
  color: #dc3545;
}
.hint-text {
  font-size: 12px;
  color: #888;
  margin-top: 4px;
  margin-bottom: 0;
}
.form-group input,
.form-group textarea {
  width: 100%;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 6px;
  font-size: 14px;
  font-family: inherit;
  box-sizing: border-box;
}
@media (prefers-color-scheme: dark) {
  .form-group input,
  .form-group textarea {
    background: #333;
    border-color: #555;
    color: #f6f6f6;
  }
}
.form-group textarea {
  resize: vertical;
  min-height: 150px;
}
.button-row {
  display: flex;
  gap: 12px;
  justify-content: flex-end;
  margin-top: 20px;
}
.primary-button {
  background: #24c8db;
  color: white;
  padding: 10px 20px;
  border: none;
  border-radius: 6px;
  cursor: pointer;
}
.primary-button:hover:not(:disabled) {
  background: #1ba8b8;
}
.primary-button:disabled {
  background: #999;
  cursor: not-allowed;
}
.secondary-button {
  background: #6c757d;
  color: white;
  padding: 10px 20px;
  border: none;
  border-radius: 6px;
  cursor: pointer;
}
.secondary-button:hover {
  background: #5a6268;
}
</style>
